ubports/ubports-installer

cli.js
package.json
src/adb.js
src/devices.js
src/html/index.ejs
src/html/modals/developer-mode.ejs
src/html/modals/install.ejs
src/html/modals/options.ejs
src/html/modals/password.ejs
src/html/modals/select-device.ejs
src/html/scripts/dots.ejs
src/html/scripts/main.ejs
src/html/scripts/root.ejs
src/html/scripts/ui.ejs
src/html/views/done.ejs
src/html/views/install.ejs
src/html/views/installing.ejs
src/html/views/not-supported.ejs
src/html/views/reboot.ejs
src/html/views/wait-for-device.ejs
src/system-image.js

This adds:  
- Switch to UBports 
- Option to wipe 
- Some redesign 
- UI manager class 
- Splitting of html scripts

Complete overhaul

---

build.js

Add fastboot and adb dependency to deb file

---

package.json

Update electron-builder version

---

src/devices.js
src/system-image.js
src/utils.js

Change macOS cache path and rename function

---

snap/snapcraft.yaml

Updated description and summary

---

src/utils.js

This is super embarrassing, i broke it in #132. Blame Marius!

Fix windows path #149

---

src/devices.js
src/html/index.pug
src/html/modals/no-network.pug
src/html/scripts/main.pug

Fix devices sort

---

build.js
cli.js
package.json
src/adb.js
src/devices.js
src/fastboot.js
src/system-image.js
src/utils.js

Renames all methods to have English written properly. Also includes
the changes in the dependency upstream system-image-module.
Should solve issue #166.

Fixes methods typos in project

---

src/devices.js

Catch blacklist not defined

---

src/devices.js
src/html/views/install.pug
src/html/views/not-supported.pug
src/html/views/reboot.pug
src/html/views/wait-for-device.pug

Catch reboot error

---

.gitignore
TODO
src/system-image.js

This together with https://github.com/ubports/system-image-node-module/pull/7 should fix #231.

Fix system image download location

---

src/html/modals/developer-mode.pug
src/html/views/wait-for-device.pug

Shortened welcome text. Text gets rendered bigger on some platforms causing the page to overflow.

Shorter welcome text

---

src/adb.js
src/html/modals/developer-mode.pug
src/html/views/wait-for-device.pug

Fix #262 Fix  #259 Fix #346 Fix #110
Maybe.
Also don't log NaN% progress, because that's stupid.

Hello darkness my old friend

---

package.json
snap/snapcraft.yaml
src/html/modals/options.pug
src/html/scripts/main.pug

This should fix some of the cross-firing events. Also I made some small text tweaks.

Try and tame event crossfire

---

src/html/index.pug
src/html/modals/error.pug
src/html/modals/new-update.pug
src/html/scripts/main.pug
src/utils.js

Notify users if there is an update. This should hopefully reduce the number of duplicate bug reports in the future...

Notify about updates

---

README.md
src/adb.js
src/devices.js
src/html/index.pug
src/html/modals/options.pug
src/html/modals/windows-drivers.pug
src/html/scripts/main.pug
src/html/scripts/ui.pug
src/utils.js

Sorry, should have done one issue per PR. I went a little crazy...

Allow users to set custom adb

---

build.js
package.json

See issue #288 
unzipper is a fork of unzip and still maintained.

Replace unzip with unzipper

---

setup-dev.sh

Tested on
* openSUSE Leap 15.0
* Ubuntu 16.04
* Debian 8

Use correct nodejs package when setting up to run from source on openSUSE

---

package-lock.json
package.json
src/html/index.pug
src/html/scripts/main.pug
src/html/scripts/root.pug
src/html/scripts/ui.pug
src/main.js
src/utils.js

fixed bug issue #245 where version was not displayed in the UI. program version now displays in window title and In the header of the UI.
version is gotten from package.json file and applied automatically on program load

Fixed version display

---

setup-dev.sh

Fixes #521 
New PR incorporating the last commit on master fixing the npm package dependencies.

Use correct build dependencies for Ubuntu >= 18.04

---

src/html/modals/error.pug

Link to download the latest version was directing to the issues page.

fix installer link

---

src/devices.js
src/fastboot.js
src/html/scripts/main.pug
src/html/views/reboot.pug

Instruct a manual reboot if the device isn't detected after 15 seconds, catch another connection lost error, succumbence to tab width ocd in devices.js. Fixes #207.

Reboot timeout

---

.travis.yml
Jenkinsfile
build.js
package.json
snap/snapcraft.yaml
src/utils.js

Build script improvements

---

src/html/views/done.pug
src/main.js

add "Flash another!"-button

---

package-lock.json
package.json

Bump version of mocha, remove unneeded dep, commit package-lock as recommended in modern npm

Resolve vulnerabilities

---

package.json
src/css/style.css
src/html/index.pug
src/html/scripts/ui.pug

Add donate button to top bar

---

package-lock.json
setup-dev.sh
src/devices.js

This is an ugly hardcode to display edge and hide vivid. Fixes #554.
Also bumped some dependencies and fixed the setup-dev for disco. Please don't squash.

Display edge

---

README.md

[✓] Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
[✓] All new code requires tests to ensure against regressions
I have been a markdown user for a couple years as of now. What I noticed from the original README.md file was that sections were a tiny bit too squished together and I believed I could change it to look more nice. (I'm hoping to add more changes to further projects you all have made).
Here is what I did:
* Added a couple small icons near the **Title**, **How to install**, The OS names (linux, windows, and mac).
* Added emojis near **Usage**, **Toubleshooting**, and **How to run the program from source**.
* Added lines between sections to make it seem …

Change to README.md (Hello again!)

---

package-lock.json
package.json
src/utils.js

Was due to an api change at paste.

Fix log link, resolves #879

---

package-lock.json
package.json
src/main.js

Make sure adb does not live on as a zombie process

---

src/main.js

Yes, this should not be used for normal error handling, but i need those sweet bug reports.

Gotta catch 'em all! (the errors)

---

build.js
buildconfig-generic.json
snap/snapcraft.yaml
src/main.js
src/utils.js

We should not export from the snap, but package executables directly.

Fix snap build

---

src/html/views/done.pug

Needs to be properly fixed later.

Temporarily disable flash another due to #963

---

src/main.js

Pass log function to adb and fastboot

---

src/main.js
src/utils.js

I already love how much easier this is going to make debugging

Log all fastboot and adb commands, resolves #717

---

package-lock.json
package.json
src/devices.js

Especially important while we don't have udev rules straightened out!

Timeout wait steps

---

package-lock.json
package.json
src/main.js
src/system-image.js

This implements the recent changes in the android-tools module that fix #1008 and adds logging for whether data exists as expected. I don't want to go further than logging with the latter for now, since i'm not 100% sure it'll work on every device yet.

Improve cache wiping

---

src/devices.js
src/html/modals/no-network.pug
src/main.js
src/utils.js

Fix a couple of connectivity-related issues.

Connectivity

---

package-lock.json
package.json
src/devices.js
src/html/modals/options.pug
src/system-image.js

An issue i introduced in #1054.

Fix splitbrain

---

src/img/formfactor/computer.svg
src/img/formfactor/laptop.svg
src/img/formfactor/phone.svg
src/img/formfactor/tablet.svg
src/img/formfactor/watch.svg
src/img/media/sdcard.svg
src/img/media/thumbdrive.svg

To enable the work on #979, i'd like to get this in now.

Add suru icons to work from for #979

---

src/html/scripts/ui.js
src/main.js

Decided to do this myself, because it's annoying. We have enough good first issues anyways.

Hide animations instantaneously, fixes #1024

---

src/devices.js

Return functions not promises in installStep()

---

package-lock.json
package.json
src/main.js

Handle adb startup errors

---

src/html/views/done.pug

Replaces old get-involved page with new join-us page

---

package-lock.json
package.json
src/main.js

As our ancient version is running out of support, this is getting kind of urgent. Resolves #1020.

Upgrade to electron 6

---

src/html/scripts/root.js
src/html/scripts/ui.js

Basing on the issue created 15 hours ago:
https://github.com/ubports/ubports-installer/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
I am doing my first contribution to the open source community. I hope it serves its purpose.
I refactored the code and although I spotted some minors bugs I left untouched as the issue requested it was to remove the jQuery lib from the code and I have done it following the previous coding style (structure). Please let me know if any doubt arises.

removing jQuery dependency on code and use vanilla js.

---

src/html/scripts/ui.js

I am sorry. I have introduced an small typo error in this specific function. I was double checking the code looking for improvements and noticed.

Fixed typo on setAttribute method call

---

package.json
src/css/style.css
src/html/modals/error.pug
src/html/modals/new-update.pug
src/html/modals/oem-lock.pug
src/html/modals/options.pug
src/html/modals/unlock.pug
src/html/scripts/dots.js
src/html/scripts/ui.js
src/html/views/done.pug
src/html/views/not-supported.pug
src/html/views/select-os.pug
src/html/views/user-action.pug
src/html/views/wait-for-device.pug

I have removed all jQuery code from this repo. I should have checked before, my bad... This branch also come from master, so let me know when you approve either branch (please just update one and let me know) so I rebase to the most updated branch and you do not have to merge everything and will be a clean fast forward (one on top of the other).
Hope everything is solved now.

jQuery removed of all templates (pug) and dot.js

---

package.json
src/css/style.css
src/html/modals/error.pug
src/html/modals/new-update.pug
src/html/modals/oem-lock.pug
src/html/modals/options.pug
src/html/modals/unlock.pug
src/html/scripts/dots.js
src/html/scripts/ui.js
src/html/views/done.pug
src/html/views/not-supported.pug
src/html/views/select-os.pug
src/html/views/user-action.pug
src/html/views/wait-for-device.pug

Reverts ubports/ubports-installer#1143

Revert "jQuery removed of all templates (pug) and dot.js"

---

src/html/scripts/ui.js

Reverts ubports/ubports-installer#1141

Revert "Fixed typo on setAttribute method call"

---

src/html/scripts/root.js
src/html/scripts/ui.js

Reverts ubports/ubports-installer#1140

Revert "removing jQuery dependency on code and use vanilla js."

---

src/devices.js

To be merged with https://github.com/ubports/installer-configs/pull/34

Implement fastboot:format step, resolves #1303

---

src/devices.js

Fixes #1368 if merged with https://github.com/ubports/promise-android-tools/pull/35

Properly detect oem lock

---

README.md
setup-dev.sh

Also specify supported distros in the README for clarity
Closes #1345

Improve the setup-dev tool to handle Arch

---

buildconfig-generic.json
package-lock.json
package.json
snap/snapcraft.yaml
src/bugreport.js
src/utils.js

Small stuff that turned up in user testing

Whatisbrokenwillbefixedagain

---

src/main.js

Quit on macos, fixes #1047

---

src/main.js

Fix #1320. This should work universally.

Support both absolute and relative paths, fix #1320

---

src/devices.js
src/main.js
src/pug/index.pug
src/pug/views/manual-download.pug

Resolve #1456. Prerequisite for #1305 and #1377.

Add manual_download step, resolves #1456

---

package-lock.json
package.json
src/devices.js

can be used like `{ "type": "fastboot:set_active", "slot": "a" }`

add fastboot:set_active step, resolves #1469

---

package-lock.json
package.json
src/devices.js
src/main.js
src/pug/index.pug
src/pug/modals/result.pug
src/pug/scripts/ui.js
src/report.js
src/system-image.js
src/utils.js

see https://github.com/ubports/promise-android-tools/pull/49

Near-rewrite of promise-android-tools

---

src/main.js

This should help with #1517 later

Log tool path for debugging

---

src/main.js

Ignore empty data object

---

src/core/api.js

This sets the correct api target for v2

Set new api target

---

src/core/plugins/index.js
src/core/plugins/index.spec.js

Ensure plugin and provider exist when resolving remote_values

---

src/ui/views/ManualDownload.svelte

See #2179. No further adjustments in [plugin.js](https://github.com/ubports/ubports-installer/blob/master/src/core/plugins/core/plugin.js) required.

Fix manual download file input

---

snap/snapcraft.yaml

https://snapcraft.io/docs/snapcraft-extensions

snap: update to use extension

---

src/lib/updater.js
src/main.js

These are small changes, which are grouped in a single PR for sake of not spamming multiple PRs.
If you want them split up or commits dropped, please let me know :)

various changes, fixes and improvements

---

__mocks__/open-cuts-reporter.js
__mocks__/systeminformation.js
package-lock.json
package.json
src/lib/reporter.js
src/lib/reporter.spec.js

Fixes #2516, which caused newlines in device link
Link to config files
Only link to devices page for ubuntu touch devices
mention if a local config file was used

Improve bug report template structure

---

src/ui/views/Done.svelte
src/ui/views/SelectOs.svelte

Picking some low hanging fruits.I would skip action images for now since they differ between the devices. Closes #979.

Add pictures for different device categories

---

package-lock.json
package.json

Updates dependencies to resolve security issues.

deps: upgrade progressive-downloader to 1.0.8

---

package-lock.json
package.json

Release 0.11

---

snap/snapcraft.yaml

snap: Use number instead of bool for environment variable
