README.md

Had today a difficult case of user not being able to use any of the installer options. Turns out that udev rules are missing. We must provide clear and concise information about this tricky dependency.

Added section about how to add udev rules necessary for some devices

---

src/adb.js

When I try to install with Mac OS High Sierra
```
adb -P PORT push /Users/bar/Library/Application Support/ubports/pool/ubports-foo.tar.xz /cache/recovery/
```
Above cmd cause an error, following workaround may fix this issue.
```
adb -P PORT push '/Users/bar/Library/Application Support/ubports/pool/ubports-foo.tar.xz' /cache/recovery/
```
Actually, this fix may fail if file path contains char `'`.

Workaround file path with whitespaces

---

src/adb.js
src/fastboot.js
src/utils.js

This should fix #88 by introducing a helper function and escaping the password everywhere.
Are you fine with the function name? I can remove the `cmd` parameter if you'd prefer it to just return the correct sudo command. 
Note that it currently appends an unnecessary space when called with empty `cmd` parameter.
Is `utils` the correct place for the function?

Properly escape password everywhere

---

src/adb.js

As reported by Rudy on Telegram, the Pro 5 sometimes reports itself as PRO5. This adds the alias.

Add alias for PRO5 = turbo

---

package.json
src/html/modals/error.pug
src/html/modals/new-update.pug
src/html/modals/options.pug
src/html/modals/windows-drivers.pug
src/html/scripts/main.pug
src/html/scripts/root.pug
src/html/views/done.pug
src/html/views/install.pug
src/html/views/not-supported.pug
src/html/views/wait-for-device.pug

That obscure bug happened in Windows x64 as well as x32. The root cause was the `openurl` module which spawns `explorer.exe` with the URL as the argument, that it treats it as a file path. Windows has a limit of 260 characters long for paths and it truncates the error message as a result (welp, windows is windows :confused:)
More info here: https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file#maximum-path-length-limitation
The fix is as easy as to use the methods that provide electron. electron.shell.openExternal() does the trick and it has a limit of 2081 characters long on Windows, so as long as the error report URL doesn't exceed that limit we're good :satisfied:
More info: https://electronjs.org/docs/api/shell#shellopenexternalurl-options-callback
Fixes #224

Fix broken error report in Windows

---

src/html/scripts/main.pug

Refer back to: https://www.ecenglish.com/learnenglish/when-use-a.
We also had this discussion in the [FluffyChat room](https://riot.im/app/#/room/!KzHjwnhdwaLkjewCCh:matrix.org/$15467341922186675gAlbR:matrix.org).

Update `main.pug` with an improved expression `an usb` => `a USB`

---

src/adb.js
src/fastboot.js
src/utils.js

- add function "hidePw" to String prototype for convenience
- if stdout/stderr are too long, log last lines instead of "overflow"
- log additional commands
- add error logging where fastboot errors were silently ignored

Extend error output

---

src/system-image.js

This hit me on angler: the main fstab has much more entries than what the recovery has as mountpoints, and also recovery does not mount many of the exotic partitions.
I think its finde not to mount anything here. The userdata, system and cache partitions will always be available. And thats the only things we should need.

Do not mount all partitions

---

src/utils.js

This should fix #1451 (and previously #847). This went unnoticed, because these paths only occur when the account is set up connected to a Microsoft account. The previous attempt (#1076) was abandoned, this one should be better.

Wrap executable in double quotes, fixes #1451

---

package-lock.json
package.json
src/devices.js

This adds promise-andorid-tools 3.0.0, thus resolving #1459. No config was using `--force`, so this does not break the API in a noticeable way.
The dependency update also includes prerequisites for backup and restore functionality (#141).

Implement additional fastboot flags, resolves #1459

---

src/system-image.js

this ensures the command be evaluated on the device, which will always be a bourne shell

Make sure command gets evaluated on the device, resolves #1474

---

package-lock.json
package.json
src/main.js
src/pug/index.pug
src/pug/modals/result.pug
src/pug/modals/udev.pug
src/pug/modals/windows-drivers.pug
src/pug/scripts/ui.js
src/report.js

- Replace LocalStorage with electron-store and add more settings options that use it to the global menu, resolves #694.
- Store OPEN-CUTS tokens and implement a UI for it (part of #1432).
- Fix #1476, where pasted logs were sometimes invalid
- Implement a UI to create bug reports, resolves #955.
- Unobtrusively ask users to report successful runs to OPEN-CUTS, resolves #1432.
- Improve "never ask again" functionality

Permanent settings and better automatic reporting

---

build.js
src/main.js

Since child_process.spawn() can not access files inside asar packages (https://github.com/electron/electron/issues/9459), we need to unpack a whole bunch of stuff. Super annoying. but this fixes #1517.

Unpack libraries related to promise-android-tools

---

package-lock.json
package.json
src/devices.js
src/main.js
src/pug/index.pug
src/pug/modals/oem-lock.pug
src/pug/modals/options.pug
src/pug/views/select-os.pug

This upgrades to the latest point release of promise-android-tools, which fixes #1533, fixes #1506, and fixes #1498.
Fixes #1173 where it was possible to hide the config modal.
Fixes #983 and fixes #1317 where we could not reconnect to offline or unauthorized devices.
Handle some unlocking errors, part of #1479.

Improve android tools handling

---

.github/workflows/ci.yml

We had a non-breaking race conditions where the upload fails on some artifacts and github actions sends out unnecessary emails due to this.

Only run release script once

---

__mocks__/electron.js
__mocks__/open-cuts-reporter.js
__mocks__/ubuntu-pastebin.js
package-lock.json
package.json
src/lib/report.js
src/lib/report.spec.js
src/main.js
src/report.js

Separated out two new modules:
- [ubuntu-pastebin](https://www.npmjs.com/package/ubuntu-pastebin)
- [open-cuts-reporter](https://www.npmjs.com/package/open-cuts-reporter)
Also moved the reporting file to the lib directory and added some basic tests. This concludes the basics of the modularization refactoring and code cleanup. The plan is to get this out to QA and finalize the work in subsequent point releases.

Move report.js to lib

---

src/devices.js

That hack is no longer required after https://github.com/ubports/installer-configs/pull/48 is merged.

Deprecate checksum strings in favor of checksum objects

---

src/core/plugins/core/plugin.js

The whole block beginning with `.then(downloadedFilePath` and ending with `copyFile()` (^1) was never going to resolve its promise with an actual return value.
That meant that that `checkFile()` was being called before any of the promise functions inside the previous block had
the chance to run, therefore the copied file was not yet available, leading to checkFile trying to verify a non-existent path, leading to a checksum mismatch error.
Solution is to make the whole block return something, in this case the value of the last chained promise.
Solves:
```
error: Error: core:manual_download: Error: checksum mismatch
```
Fixes https://github.com/ubports/ubports-installer/issues/1754
^1:
https://github.com/ubports/ubports-installer/blob/95745e519351adc3189e7e285a553bc6c1e5100a/src/core/plugins …

plugins: manual_download: Resolve copyFile promise

---

src/core/helpers/asarLibs.js
src/core/plugins/core/plugin.js
src/core/plugins/core/plugin.spec.js

This enables adding a `name` property to file objects in the `core:download` action. Also see https://github.com/ubports/installer-configs/pull/84. Resolves #1611.
cc @Vince1171

Download rename

---

setup-dev.sh

Adds install options for Fedora Linux. 
Only tested on Fedora 33, and the version where `yum` is replaced by `dnf` comes from here:https://github.com/rpm-software-management/dnf#installing
To verify the installation was working I ran:
```
$ npm start -- -h
> ubports-installer@0.8.9-beta start /home/ccastro/Projetos/ubports-installer
> npm run prerender && electron . "-h"
> ubports-installer@0.8.9-beta prerender
> npx gulp pug
[18:10:13] Using gulpfile ~/Projetos/ubports-installer/gulpfile.js
[18:10:13] Starting 'pug'...
[18:10:15] Finished 'pug' after 1.51 s
Usage: npm start -- [-f <file>] [-v[v] [-d]
UBports Installer (0.8.9-beta) source for linux
GPL-3.0 UBports Foundation <info@ubports.com>
The easy way to install Ubuntu Touch on UBports devices. A friendly cross-platform Installer for …
```

adds Fedora to setup-dev.sh

---

src/lib/updater.spec.js

add tests to `isOutdated`, `isPrerelease` and `getLatestVersion` methods. Small progress in #1572 .
New test coverage in `src/lib`:

adds tests to updater.js

---

src/lib/reporter.js

Add link to device page (if it's identified) in bugreport

---

__mocks__/systeminformation.js
rollup.config.mjs
src/App.svelte
src/lib/reporter.spec.js

The `getEnvironment` call is very slow on windows, causing the tests on windows to time out and fail the test suite.
There is also a change to rollup to fix build breakage because of code splitting attempts.
Also fix a case typo.

Fixes for building, typo and windows ci

---

src/ui/modals/specific-modals/PromptModals.svelte

We need to bind to checked state instead of value, see:
- https://svelte.dev/tutorial/checkbox-inputs
Issue: https://github.com/ubports/ubports-installer/issues/2494

ui: PromptModals: fix checkboxes

---

package-lock.json
package.json
src/core/plugins/fastboot/plugin.js
src/core/plugins/fastboot/plugin.spec.js

Devices, which are launching with Android 10 and higher, are required to implement [Dynamic Partitions](https://source.android.com/devices/tech/ota/dynamic_partitions/implement).
This requires a different workflow when installing, such as resizing super partitions or rebooting to userspace fastboot ([fastbootd](https://source.android.com/devices/bootloader/fastbootd)) mode to flash logical partitions located withing the physical super partition.
This PR bumps `promise-android-tools` to 4.0.8, which supports additional fastboot commands, and wires up new actions to be used by device specific installer configs, like:
```
- fastboot:reboot_fastboot:
```
```
- fastboot:reboot_recovery:
```
```
- fastboot:wipe_super:
image:
file: "super_empty.img"
group: "firmware"
```

Implement additional fastboot actions

---

__mocks__/axios.js
src/lib/paste.js
src/lib/paste.spec.js
src/lib/reporter.js
src/lib/reporter.spec.js

In case OPEN-CUTS fails, we can still look at the paste this way. Works using [SnipBin](https://snip.hxrsh.in/api-docs.md), since ubuntu pastebin does not allow anonymous pastes any more.

Bring back pasted log files in bug reports

---

package-lock.json
package.json
src/core/core.js
src/core/core.spec.js
src/lib/mainEvent.js

allow specifying compatible_installer per os

---

README.md
package-lock.json
package.json
src/core/plugins/core/plugin.spec.js
src/core/plugins/index.spec.js
src/core/plugins/systemimage/api.js
src/core/plugins/systemimage/plugin.spec.js
src/lib/cli.js

supercedes #2101.
Use `npm start -- --systemimage "https://wherever.xyz"` for custom settings.

Introduce CLI flag for systemimage server urls

---

src/core/core.js
src/core/plugins/index.js
src/core/plugins/index.spec.js
src/core/plugins/plugin.js
src/core/plugins/systemimage/api.js
src/core/plugins/systemimage/api.spec.js
src/core/plugins/systemimage/plugin.js
src/core/plugins/systemimage/plugin.spec.js
src/lib/menuManager.js
src/lib/settings.js
src/ui/modals/specific-modals/PromptModals.svelte

hidden channels are presented in a separate section at the end of the dropdown.
Replaces #2432, thanks to @mariogrip for the idea.

Show hidden systemimage channels

---

src/core/plugins/adb/plugin.js
src/core/plugins/adb/plugin.spec.js
src/core/plugins/fastboot/plugin.js
src/core/plugins/fastboot/plugin.spec.js
src/core/plugins/systemimage/plugin.js
src/core/plugins/systemimage/plugin.spec.js

Resolves #2505. Specified in https://github.com/ubports/installer-configs/pull/178.
Example:
```yml
- adb:assert_prop:
prop: "ro.ubuntu.recovery"
value: "true"
- fastboot:assert_var:
variable: "ro.ubuntu.recovery"
value: "true"
- adb:assert_prop:
prop: "ro.ubuntu.recovery"
regex:
pattern: "true"
flags: "i"
- fastboot:assert_var:
variable: "ro.ubuntu.recovery"
regex:
pattern: "true"
flags: "i"
- systemimage:install:
verify_recovery: true
```

Add fastboot:assert_var and adb:assert_prop actions for #2505

---

src/core/plugins/systemimage/plugin.js
src/core/plugins/systemimage/plugin.spec.js

worked if nothing was passed, threw an error if null was passed. well. at least it was caught within two hours by [opencuts](https://ubports.open-cuts.org/run/623d2333bfb7110008fb491f) :)

Fix #2536: Cannot destructure property 'verify_recovery'

---

src/core/core.js
src/core/core.spec.js
src/core/plugins/adb/plugin.js
src/core/plugins/adb/plugin.spec.js

Fix issue where `adb:reconnect` returned non-null.
Make sure `core.run()` does not try to map something that is not steps.
Seen in https://ubports.open-cuts.org/run/623e5981bfb7110008fb5d98:
```
verbose: running step {"actions":[{"adb:reconnect":{}}]}
verbose: running adb action reconnect
command: exec: {"cmd":["adb","-P",5037,"reconnect"],"stdout":"reconnecting 86a0ca6b0408 [recovery]","stderr":"adb server version (40) doesn't match this client (41); killing...\r\n* daemon started successfully"}
command: exec: {"cmd":["adb","-P",5037,"wait-for-any-any"],"stderr":"adb server version (40) doesn't match this client (41); killing...\r\n* daemon started successfully"}
command: exec: {"cmd":["adb","-P",5037,"get-state"],"stdout":"recovery"}
debug: attempting to handle TypeError: steps.map is …
```

Fix bug in `adb:reconnect`

---

src/core/plugins/adb/plugin.js
src/core/plugins/adb/plugin.spec.js
src/core/plugins/fastboot/plugin.js
src/core/plugins/fastboot/plugin.spec.js

Some shit i found while working on https://github.com/ubports/installer-configs/pull/182.

Fix `adb:update` action and allow `adb:shell` action to take an array

---

setup-dev.sh

Add install command for `nodejs` (`npm` included) on [Void Linux](https://voidlinux.org).

setup-dev.sh: Add Void Linux support

---

src/core/plugins/core/plugin.js
src/ui/views/ManualDownload.svelte

After manually downloading a file, a checksum test is performed on the
file. For large files this test can take some time (seconds), and
there's currently no indication in the UI that this is taking place.
This change disables the file selector and "Continue" buttons during the
checksum test, changing the text in the button to "Checking..." instead.
This provides immediate feedback for the user and avoids the confusion
of allowing them to still use the buttons while the check is taking
place.

Disable manual download buttons during checksum test

---

src/ui/views/WaitForDevice.svelte

When the app first starts up there can be a slight delay before the
configuration files have been downloaded and adb starts up.
During this time, if the "Select device manually" button is pressed by
the user, the device selection combobox will be empty, which can be
confusing for the user.
This change disables the button until initialisation is complete,
displaying a "Loading device list..." message in the meantime.

Delay activation of manual device select button

---

src/ui/partials/Footer.svelte

Add unit to speedText span

---

src/main.js

This prevents rendering getting slow when switching to other
applications while installing, which results in the installer
interacting with the device while GUI is trying to catch up
with the installation process.

main: do not lower priority of rendering when in background

---

src/App.svelte
src/core/core.js
src/core/core.spec.js
src/lib/__mocks__/mainEvent.js
src/main.js
src/main.spec.js

When the flashing process completes the user is asked if they want to
flash another device. Currently the button seems to do nothing; these
changes return the app back to the start screen to allow the user to
attempt another flashing process.

Fix restart button when Done

---

src/core/core.js
src/core/core.spec.js
src/lib/__mocks__/mainEvent.js
src/lib/errors.js
src/lib/errors.spec.js
src/lib/reporter.js
src/lib/reporter.spec.js
src/main.spec.js

Users are often reluctant to report the first error they run into and chose to ignore it. If something does not work, they report it later and the error gets buried in the log. We should keep track of these and include them in the bug reports.
If any errors have been ignored, the PASS reporting option should be disabled. Even if everything worked, the correct status to report in this case is WONKY, as a workaround was required.

 Keep track of ignored errors, resolves #2533 

---

package-lock.json
package.json
src/core/plugins/fastboot/plugin.js
src/core/plugins/fastboot/plugin.spec.js

This implements the following new action:
```
- actions:
- fastboot:create_logical_partition:
partition: "partition_name"
size: 3221225472
- fastboot:delete_logical_partition:
partition: "partition_name"
- fastboot:resize_logical_partition:
partition: "partition_name"
size: 3221225472
```
These actions are required for certain devices with
dynamic partitions, like the Fairphone 4.
`promise-android-tools` needs support for these actions:
- https://github.com/ubports/promise-android-tools/pull/66
Then we need a new release of it and dependencies need to be updated.

plugins: fastboot: add commands for interacting with logical partitions

---

src/ui/views/UserAction.svelte

Currently the user action link only gets displayed in the popup view but
not in the full-page view that you get from a fallback action. Fix that.
Before the "More..." button just wasn't present.

Display provided link from user action

---

src/core/core.js
src/core/plugins/index.js
src/core/plugins/index.spec.js
src/core/plugins/postmarketos/api.js
src/core/plugins/postmarketos/api.spec.js
src/core/plugins/postmarketos/plugin.js
src/core/plugins/postmarketos/plugin.spec.js

This PR adds support for flashing postmarketOS to supported devices, using images hosted on https://images.postmarketos.org. The images are indexed via https://images.postmarketos.org/bpo/index.json using the BPO schema: https://gitlab.com/postmarketOS/build.postmarketos.org/-/blob/master/test/testdata/index.schema.json
As it stands it's possible to pick the release channel (edge, v21.12, etc) and user interface of choice (phosh, plasma mobile etc), the images download successfully, but I'm having some trouble decompressing the .xz files.
For now, this will only be able to support some Android devices from the main or community categories: https://wiki.postmarketos.org/wiki/Devices e.g. the OnePlus 6 and PocoPhone F1. Devices like the PinePhone require extra functionality for flashing.
My …

plugins: initial postmarketOS support

---

package-lock.json
package.json

This PR marks version as `0.9.7-beta` to prepare for a new installer release.
It also updates dependencies once again, pulling in a new version of `promise-android-tools` (4.0.13), which has a fastboot getvar fix for windows devices as well as new reboot targets for adb.

release: 0.9.7-beta

---

src/core/plugins/postmarketos/plugin.js
src/core/plugins/postmarketos/plugin.spec.js

Fallback to default config name, if not set.
This is for example needed for Fairphone 4 (FP4 vs fp4).
/cc @z3ntu

plugins: pmOS: allow passing in codename

---

src/core/core.js
src/core/helpers/session.js
src/core/helpers/session.spec.js
src/core/plugins/index.js
src/core/plugins/index.spec.js
src/lib/reporter.js
src/lib/reporter.spec.js
src/lib/window.js
src/lib/window.spec.js

session store to track executed actions

---

src/core/plugins/systemimage/api.js
src/core/plugins/systemimage/plugin.js
src/core/plugins/systemimage/plugin.spec.js

This makes the channel list sort by stability (grouped by major version)
to avoid the unstable latest one being the default which confuses new
users.
Also makes labels shorter by removing the arch/halium version from the
name.
And hides /edge to avoid further confusion.

plugins: systemimage: sort channels by stability, nicer labels, no edge

---

src/core/plugins/lineage_os/api.js
src/core/plugins/lineage_os/api.spec.js

The response is sorted from newest to oldest version. We are selecting the last entry (length - 1), which is the oldest version.
This results in devices with support for multiple lineage versions (eg 19.1, 20.0) to retrieve the older version (eg 19.1) which is in most cases unsupported.
If the device only supports a single version, it selects older builds as well, which will ask to update again.
Use the first entry of the response to install the latest version.
Fixes: https://github.com/ubports/ubports-installer/issues/3141

plugins: lineage: select latest build instead of oldest

---

src/lib/updater.js

Fixes the comparison in updater to be semver-compatible.
I'd recommend bumping the version to `0.10.0` to make versions `0.9.2`-`0.9.9` show the update prompt.
Keep in mind that in semver `0.0.1` is more recent than `0.0.1-beta` - and we should make sure the `package.json` version is in sync with the tag names, it will always scream for an update if it's a `0.10.0` tag and `0.10.0-beta` in `package.json`

lib: updater: fix semver comparison

---

src/core/core.js

Looks like this is the last thing that has to be reset.

core: re-create plugin index on reset

---

package-lock.json
package.json

Version 2.x has issues with bigger files, probably due to reading the whole file at once instead of streaming - quick patch to fix installation for some devices while we look into it (that's one of our packages too).

deps: downgrade progressive-downloader to 1.0.7

---

src/core/plugins/postmarketos/api.js
src/core/plugins/postmarketos/api.spec.js
src/core/plugins/postmarketos/plugin.js
src/core/plugins/postmarketos/plugin.spec.js

BPO now has pretty_name fields for interfaces, releases (and devices). Use them and remove the hardcoded UI name mappings.

postmarketos: use pretty_name for display labels

---

snap/snapcraft.yaml

Stage the adb & fastboot packages and reference them from the installer.

snap: Use adb & fastboot from the snap package

---

snap/snapcraft.yaml

Otherwise spawning fastboot yields a linking error.

snap: Extend LD_LIBRARY_PATH
